# Generated by Django 4.1.2 on 2022-11-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_date',
            field=models.CharField(choices=[(None, 'Выберите дату записи'), ('tomorrow_12', '13.11 в 12:00'), ('tomorrow_16', '13.11 в 16:00'), ('tomorrow_20', '13.11 в 20:00'), ('d_a_tomorrow_12', '14.11 в 12:00'), ('d_a_tomorrow_16', '14.11 в 16:00'), ('d_a_tomorrow_20', '14.11 в 20:00')], max_length=40, verbose_name='Дата записи'),
        ),
    ]
